name: gd-godot-engine-mono-snapcraft
license: MIT
summary: Godot Engine
description: |
  Godot Engine
base: core20
grade: stable
confinement: strict

adopt-info: gd-godot-engine-mono-snapcraft

architectures:
  - build-on: amd64

layout:
  /usr/bin/mono:
    symlink: $SNAP/usr/bin/mono
  /usr/lib/mono:
    bind: $SNAP/usr/lib/mono

apps:      
  gd-godot-engine-mono-snapcraft:
    extensions: [gnome-3-38]
    command: godot-engine-mono/godot-engine-mono
    plugs:
      - desktop
      - desktop-legacy
      - home
      - opengl
      - x11
      - unity7
      - wayland
      - browser-support
      - network
      - gsettings
      - pulseaudio
      - audio-playback

parts:
  gd-godot-engine-mono-snapcraft:
    plugin: nil
    source: https://github.com/godotengine/godot.git
    source-type: git
    override-pull: |
      snapcraftctl pull
      git checkout "$(git describe --tags `git rev-list --tags --max-count=1`)" -b latest
      snapcraftctl set-version "$(git describe --tags | sed 's/v//' | sed "s/-g/%/"  | cut -d "%" -f1)"
    override-build: |
      # Python
      python3 -c "import sys; print(sys.version)"
      pip3 install scons
      
      # Version
      python3 --version
      pip3 --version
      scons --version
      mono --version
      msbuild -version
      dotnet --list-sdks
      
      # Scons
      scons -j$(nproc) p=linuxbsd target=release_debug tools=true tests=false module_mono_enabled=yes mono_static=yes mono_glue=no
      xvfb-run ./bin/godot.x11.opt.tools.64.mono --generate-mono-glue modules/mono/glue || true
      scons -j$(nproc) p=linuxbsd target=release_debug tools=true tests=false module_mono_enabled=yes mono_static=yes mono_glue=yes
      
      cd bin
      mv godot.x11.opt.tools.64.mono godot-engine-mono
      mkdir $SNAPCRAFT_PART_INSTALL/godot-engine-mono
      mv * $SNAPCRAFT_PART_INSTALL/godot-engine-mono
    build-packages:
      - git
      - sed
      - build-essential
      - pkg-config
      - libx11-dev
      - libxcursor-dev
      - libxinerama-dev
      - libgl1-mesa-dev
      - libglu-dev
      - libasound2-dev
      - libpulse-dev
      - libdbus-1-dev
      - libudev-dev
      - libxi-dev
      - libxrandr-dev
      - yasm
      - xvfb
      - wget
      - unzip
      - mono-complete
      - python3
      - python3-pip
      - msbuild
      - dotnet-sdk-6.0
    stage-packages:
      - mono-complete
      - msbuild
      - dotnet-sdk-6.0
      - libgl1-mesa-dri
      - libglu1-mesa
      - libgl1-mesa-glx
      - libgles2-mesa
      - libflac8
      - libxcursor1
      - libxi6
      - libxinerama1
      - libxrandr2
      - libxrender1
      - libasound2
      - libasyncns0
      - libogg0
      - libpulse0
      - libsndfile1
      - libtheora0
      - libvorbis0a
      - libvorbisenc2
      - libvorbisfile3
      - libwebp6
    stage-snaps:
      - code/latest/stable

package-repositories:
  - type: apt
    components: [main]
    suites: [stable-bionic]
    key-id: 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
    key-server: hkp://keyserver.ubuntu.com:80
    url: https://download.mono-project.com/repo/ubuntu
    
  - type: apt
    formats: [deb]
    components: [main]
    suites: [focal]
    architectures: [amd64,armhf,arm64]
    key-id: BC528686B50D79E339D3721CEB3E94ADBE1229CF
    url: https://packages.microsoft.com/ubuntu/20.04/prod
