name: gd-godot-engine-mono-snapcraft
license: GPL-3.0
summary: Godot Engine
description: |
  Godot Engine
base: core20
grade: stable
confinement: strict

adopt-info: gd-godot-engine-mono-snapcraft

architectures:
  - build-on: amd64

layout:
  /usr/bin/mono:
    symlink: $SNAP/usr/bin/mono
  /usr/lib/mono:
    bind: $SNAP/usr/lib/mono

apps:      
  gd-godot:
    extensions: [gnome-3-38]
    command: Godot_v3.4.4-stable_mono_x11_64/Godot_v3.4.4-stable_mono_x11.64
    environment:
      LD_LIBRARY_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio:$LD_LIBRARY_PATH"
    plugs:
      - desktop
      - desktop-legacy
      - home
      - opengl
      - x11
      - unity7
      - wayland
      - browser-support
      - network
      - gsettings
      - pulseaudio
      - audio-playback

  gd-mono:
    command: usr/bin/mono

  gd-msbuild:
    command: usr/bin/msbuild

parts:
  gd-godot-engine-mono-snapcraft:
    plugin: nil
    source: https://github.com/godotengine/godot.git
    source-type: git
    override-pull: |
      snapcraftctl pull
      git checkout "$(git describe --tags `git rev-list --tags --max-count=1`)" -b latest
      snapcraftctl set-version "$(git describe --tags | sed 's/v//' | sed "s/-g/%/"  | cut -d "%" -f1)"
    stage-snaps:
      - dotnet-sdk/latest/stable
    stage-packages:
      - libgl1-mesa-dri
      - libglu1-mesa
      - libgl1-mesa-glx
      - libgles2-mesa
      - libflac8
      - libxcursor1
      - libxi6
      - libxinerama1
      - libxrandr2
      - libxrender1
      - libasound2
      - libasyncns0
      - libogg0
      - libpulse0
      - libsndfile1
      - libtheora0
      - libvorbis0a
      - libvorbisenc2
      - libvorbisfile3
      - mono-complete
      - msbuild

  gd-godot:
    after: [gd-godot-engine-mono-snapcraft]
    plugin: dump
    source: https://github.com/godotengine/godot/releases/download/3.4.4-stable/Godot_v3.4.4-stable_mono_x11_64.zip
    override-build: |
      mv Godot_v3.4.4-stable_mono_x11_64 $SNAPCRAFT_PART_INSTALL/
      tree $SNAPCRAFT_PART_INSTALL/
    build-packages:
      - tree
    stage-snaps:
      - dotnet-sdk/latest/stable
    stage-packages:
      - libgl1-mesa-dri
      - libglu1-mesa
      - libgl1-mesa-glx
      - libgles2-mesa
      - libflac8
      - libxcursor1
      - libxi6
      - libxinerama1
      - libxrandr2
      - libxrender1
      - libasound2
      - libasyncns0
      - libogg0
      - libpulse0
      - libsndfile1
      - libtheora0
      - libvorbis0a
      - libvorbisenc2
      - libvorbisfile3
      - mono-complete
      - msbuild

package-repositories:
  - type: apt
    components: [main]
    suites: [stable-bionic]
    key-id: 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
    key-server: hkp://keyserver.ubuntu.com:80
    url: https://download.mono-project.com/repo/ubuntu
